?expr :  SIGNED_NUMBER -> num
        | "true" -> true
        | "false" -> false
        | name 
        | list
        
list  :   "(" "+" expr expr ")" -> add
        | "(" "-" expr expr ")" -> sub
        | "(" "let" "(" name expr ")"  expr ")" -> let
        | "(" "if" expr expr expr ")" -> myif
        | "(" "fun" "(" name+ ")" expr ")" -> fun
        | "(" expr expr ")" -> app

name  : CNAME -> var

%import common.CNAME
%import common.SIGNED_NUMBER
%import common.WS
%ignore WS